title:              Zeke Wattles
email:              zeke@zeke.studio
description:        Zeke Wattles / Graphic Design
author:             Zeke Wattles
baseurl:            ""
url:                "zeke.studio"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate